### PR TITLE
Issues/35

### LINKED ISSUE #35: The data type of an option with `enums` is not a union
### Search terms

_No response_

### Version

0.2.7

### Component

Options

### Playground link

_No response_

### Sample code

```ts
const opts = {
  name: {
    type: 'string',
    enums: ['hello'],
  },
} as const satisfies Options;

type Vals = OptionValues<typeof opts>;
```

### Bug description

Hover the `Vals` type and see that the resulting type is:
```ts
type Vals = {
    name: string | undefined;
}
```

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by disog**
The `EnumsDataType` was fixed to use a `ReadonlyArray` instead of a normal array.

Some improvements were made to the `TerminalString.wrapToWidth` method, so when `FORCE_COLOR` is set, it outputs text lines with better disposition of style sequences.

Closes #35

### CODE REVIEW

File: packages/tsargp/examples/demo.ts [hunk 1]
```diff
@@ -2,8 +2,25 @@
 import { ArgumentParser } from 'tsargp';
 import options from './demo.options.js';
 
+/**
+ * An interface for the option values. (To make sure that they abide by it.)
```
Comment (disog) [inline packages/tsargp/examples/demo.ts:6]:
```suggestion
 * An interface for the option values. (To make sure that they comply with it.)
```
